cart/urls.py
from django.urls import path

from .views import cart_add, cart_remove, cart_details

app_name = 'cart'


urlpatterns = [
    path('', cart_details, name='cart_details'),
    path('cart_add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart_remove/<int:product_id>/', cart_remove, name='cart_remove')
]

coupons/urls.py
from django.urls import path

from .views import coupon_apply

app_name = 'coupons'


urlpatterns = [
    path('apply/', coupon_apply, name='apply')
]

eShop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import order_create, admin_order_details, admin_order_pdf

app_name = 'orders'


urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_details, name='admin_order_details'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path

from .views import product_list, product_details


app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', product_details, name='product_details'),
]

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,
                                      label=_('Quantity'))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from coupons.forms import CouponApplyForm
from common.constants import KEY_QUANTITY


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, quantity=cd.get('quantity'), override_quantity=cd.get('override'))
    return redirect('cart:cart_details')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)
    return redirect('cart:cart_details')


def cart_details(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    for item in cart:
        item['product_update_form'] = CartAddProductForm(initial={
            KEY_QUANTITY: item.get(KEY_QUANTITY), 'override': True
        })
    return render(request, 'cart/cart_details.html', {'cart': cart,
                                                      'coupon_apply_form': coupon_apply_form})

cart/templates/cart/cart_details.html
{% extends 'shop/base.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans 'Your shopping Cart' %} {% endblock %}

{% block content %}
<h1>{% trans 'Your shopping cart' %}</h1>
<table class="cart">
    <thead>
    <tr>
        <th>{% trans 'Image' %}</th>
        <th>{% trans 'Product' %}</th>
        <th>{% trans 'Quantity' %}</th>
        <th>{% trans 'Remove' %}</th>
        <th>{% trans 'Unit Price' %}</th>
        <th>{% trans 'Price' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{item.get_absolute_url}}">
                        <img src="{% if product.image %} {{product.image.url}}{%else %} {% static 'img/no_image.png' %} {%endif%}">
                    </a>
                </td>
                <td>{{product.name}}</td>
                <td>
                    <form method="post" action="{% url 'cart:cart_add' product.id %}">
                        {% csrf_token %}
                        {{ item.product_update_form.quantity }}
                        {{ item.product_update_form.override }}
                        <input type="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form action='{% url "cart:cart_remove" product.id %}' method="post">
                        <input type="submit" value="{% trans 'Remove Item' %}">
                        {% csrf_token %}
                    </form>
                </td>
                <td>{{item.price}}</td>
                <td>{{item.total_price}}</td>
            </tr>
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>{% trans 'Subtotal' %}</td>
                    <td colspan="4"></td>
                    <td class="num">${{cart.get_total_price|floatformat:2}}</td>
                </tr>
                <tr>
                    <td>
                        "{{cart.coupon.code}}" coupon
                        ({{cart.coupon.discount}} off)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        - ${{cart.get_discount|floatformat:2}}
                    </td>
                </tr>
            {% endif %}
        {% endwith %}
    {% endfor %}
    <tr>
        <td>{% trans 'Total' %}</td>
        <td colspan="4"></td>
        <td class="num">${{cart.get_price_after_coupon|floatformat:2}}</td>
    </tr>
    </tbody>
</table>
<div class="coupon">
    <p>{% trans 'Apply a Coupon' %}</p>
    <form action="{% url 'coupons:apply' %}" method="post">
        {{coupon_apply_form}}
        {% csrf_token %}
        <input type="submit" value="{% trans 'Apply' %}">
    </form>
</div>

<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">{% trans 'Continue Shopping' %}</a>
    <a href="{% url 'orders:order_create' %}" class="button">{% trans 'Checkout' %}</a>
</p>
{% endblock %}