cart/urls.py
from django.urls import path

from .views import cart_add, cart_remove, cart_details

app_name = 'cart'


urlpatterns = [
    path('', cart_details, name='cart_details'),
    path('cart_add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart_remove/<int:product_id>/', cart_remove, name='cart_remove')
]

eShop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from .views import product_list, product_details


app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', product_details, name='product_details'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):

    name = models.CharField(max_length=64, db_index=True)
    slug = models.SlugField(unique=True, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', null=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=64, db_index=True)
    slug = models.SlugField(unique=True, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%m/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_details', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product/list.html', {
        'category': category, 'categories': categories, 'products': products
    })


def product_details(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id, slug=product_slug, available=True)
    cart_add_form = CartAddProductForm()

    return render(request, 'shop/product/details.html', {
        'product': product, 'cart_add_form': cart_add_form
    })

shop/templates/shop/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% trans 'eShop by Zee' %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">{% trans 'eShop by Zee' %}</a>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="languages">
        <p>{% trans "Language" %}:</p>
        <ul class="languages">
            {% for language in languages %}
            <li>
                <a href="/{{language.code}}/" {% if language.code == LANGUAGE_CODE%} class="selected" {% endif %}>
                    {{language.name_local}}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="subheader">
  <div class="cart">
      {% with total_items=cart|length%}
        {% if total_items > 0 %}
            {% trans 'Your Cart' %}:
            <a href="{% url 'cart:cart_details' %}">
                {% blocktrans with total=cart.get_total_price count items=total_items %}
                    {{items}} item, ${{total}}
                {% plural %}
                    {{items}} items, ${{total}}
                {% endblocktrans %}
            </a>
        {% else %}
            {% trans "Your cart is empty." %}
        {% endif %}
      {% endwith %}
  </div>
</div>
<div id="content">
  {% block content %} {% endblock %}
</div>
</body>
</html>